version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: backend
    env_file: ./backend/settings.env
    ports:
      - "5001:5000"
    depends_on:
      - db

  db:
    image: postgis/postgis
    container_name: db
    environment:
      POSTGRES_DB: landscaping_scheduler
      POSTGRES_USER: lsadmin
      POSTGRES_PASSWORD: wVaxVojCbomBaQakxe2X
    ports:
      - "5432:5432"

